#!/bin/sh
#
# rc file for Selenium
#
#
# chkconfig: 345 96 10
# description: Selenium (rhernandezm 1.0)
#
### BEGIN INIT INFO
# Provides: selenium
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: Selenium Grid 
# Description: Selenium Grid
### END INIT INFO

/usr/bin/selenium $*
